### ISSUE TITLE
Teach sweetgeany to find URLs for PRs and Issues

### ISSUE THREAD

**Issue by elextr** [geany/infrastructure#3]
Currently
```
!commit abcd123
```
generates a URL for that commit.

It would be good if say
```
!issue 1234
```
would link to the issue/pr 1234.

Although pull requests show a URL like `geany/geany/pull/1234` it seems they will also be found with `geany/geany/issues/1234` the same as other issues, so the code just needs to be the same as `!commit` code but with URL base `https://github.com/geany/geany/issues` and limiting the argument to decimal numbers.

**Comment by eht16** [comment]
Closing as SweetGeany died together with FreeNode...:(.
